# Generated by Django 5.2.1 on 2025-05-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='education_level',
            field=models.CharField(choices=[('high_school', 'High School'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='has_portfolio_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='portfolio_file',
            field=models.FileField(blank=True, null=True, upload_to='portfolios/'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='expertise_areas',
            field=models.TextField(help_text='List up to 5 writing expertise areas separated by commas'),
        ),
    ]
