# Generated by Django 5.2.1 on 2025-05-18 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.applicantprofile'),
        ),
        migrations.AddField(
            model_name='application',
            name='previous_application',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to a previous application if this is a resubmission.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resubmissions', to='applications.application'),
        ),
        migrations.AddField(
            model_name='applicationlog',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationlog',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='applications.application'),
        ),
    ]
