# Generated by Django 5.2.1 on 2025-05-21 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, help_text='External transaction ID', max_length=100, null=True)),
                ('email', models.EmailField(help_text='PayPal account email', max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('paypal', 'PayPal'), ('mpesa', 'Mpesa (Kenya only)'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card Payment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code, e.g. USD, KES', max_length=10)),
                ('confirmation_proof', models.ImageField(upload_to='payment_confirmations/')),
                ('confirmation_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('verified', 'Verified'), ('approved', 'Approved by Admin'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retry_allowed', models.BooleanField(default=True, help_text='Can user retry uploading payment proof?')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='MpesaDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, help_text='External transaction ID', max_length=100, null=True)),
                ('phone_number', models.CharField(help_text='Phone number used for M-Pesa payment', max_length=15)),
                ('mpesa_code', models.CharField(help_text='M-Pesa confirmation code', max_length=30)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_details', to='payment.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardPaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, help_text='External transaction ID', max_length=100, null=True)),
                ('card_type', models.CharField(help_text='Type of card (Visa, Mastercard, etc.)', max_length=20)),
                ('last_four', models.CharField(help_text='Last 4 digits of the card', max_length=4)),
                ('cardholder_name', models.CharField(help_text='Name on the card', max_length=100)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_details', to='payment.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankTransferDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, help_text='External transaction ID', max_length=100, null=True)),
                ('account_name', models.CharField(help_text='Name on the sending account', max_length=100)),
                ('bank_name', models.CharField(help_text='Name of the sending bank', max_length=100)),
                ('reference_number', models.CharField(help_text='Bank transfer reference number', max_length=100)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfer_details', to='payment.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='e.g., uploaded, verified, approved, rejected', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payment.payment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
