# Generated by Django 5.2.1 on 2025-05-18 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('paypal', 'PayPal'), ('mpesa', 'Mpesa (Kenya only)'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card Payment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code, e.g. USD, KES', max_length=10)),
                ('payment_details', models.JSONField(blank=True, help_text='Details shown based on payment method', null=True)),
                ('confirmation_proof', models.ImageField(upload_to='payment_confirmations/')),
                ('confirmation_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('verified', 'Verified'), ('approved', 'Approved by Admin'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retry_allowed', models.BooleanField(default=True, help_text='Can user retry uploading payment proof?')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='e.g., uploaded, verified, approved, rejected', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payment.payment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
