# Generated by Django 5.2.1 on 2025-05-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransferdetails',
            name='company_bank_account_name',
            field=models.CharField(default='Acumen Inc.', help_text="Company's bank account name", max_length=100),
        ),
        migrations.AddField(
            model_name='banktransferdetails',
            name='company_bank_account_number',
            field=models.CharField(default='123456789', help_text="Company's bank account number", max_length=50),
        ),
        migrations.AddField(
            model_name='banktransferdetails',
            name='company_bank_address',
            field=models.TextField(blank=True, help_text="Company's bank address", null=True),
        ),
        migrations.AddField(
            model_name='banktransferdetails',
            name='company_bank_branch',
            field=models.CharField(blank=True, help_text="Company's bank branch (if applicable)", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='banktransferdetails',
            name='company_bank_iban',
            field=models.CharField(blank=True, help_text="Company's bank IBAN (for international transfers)", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='banktransferdetails',
            name='company_bank_name',
            field=models.CharField(default='International Bank', help_text="Company's bank name", max_length=100),
        ),
        migrations.AddField(
            model_name='banktransferdetails',
            name='company_bank_routing_number',
            field=models.CharField(blank=True, help_text="Company's bank routing/sort code", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='banktransferdetails',
            name='company_bank_swift_code',
            field=models.CharField(default='ABCDEF12', help_text="Company's bank SWIFT/BIC code", max_length=20),
        ),
        migrations.AddField(
            model_name='cardpaymentdetails',
            name='company_card_business_name',
            field=models.CharField(default='Acumen Ink', help_text='Business name displayed on card statements', max_length=100),
        ),
        migrations.AddField(
            model_name='cardpaymentdetails',
            name='company_card_checkout_url',
            field=models.URLField(blank=True, help_text='URL for the payment gateway checkout', null=True),
        ),
        migrations.AddField(
            model_name='cardpaymentdetails',
            name='company_card_gateway',
            field=models.CharField(default='Stripe', help_text='Payment gateway for card payments', max_length=50),
        ),
        migrations.AddField(
            model_name='cardpaymentdetails',
            name='company_card_merchant_id',
            field=models.CharField(blank=True, help_text='Merchant ID for card payments', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cardpaymentdetails',
            name='company_card_public_key',
            field=models.CharField(blank=True, help_text='Public API key for the payment gateway', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mpesadetails',
            name='company_mpesa_account',
            field=models.CharField(blank=True, help_text="Company's M-Pesa account name (if applicable)", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mpesadetails',
            name='company_mpesa_business_name',
            field=models.CharField(default='Acumen Ink', help_text='Company name displayed on M-Pesa', max_length=100),
        ),
        migrations.AddField(
            model_name='mpesadetails',
            name='company_mpesa_paybill',
            field=models.CharField(default='123456', help_text="Company's M-Pesa paybill number", max_length=20),
        ),
        migrations.AddField(
            model_name='mpesadetails',
            name='company_mpesa_shortcode',
            field=models.CharField(blank=True, help_text='M-Pesa shortcode for STK Push', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paypaldetails',
            name='company_paypal_business_name',
            field=models.CharField(default='Acumen Inc', help_text="Company's business name on PayPal", max_length=100),
        ),
        migrations.AddField(
            model_name='paypaldetails',
            name='company_paypal_email',
            field=models.EmailField(default='payments@acumenink.com', help_text="Company's PayPal email for receiving payments", max_length=254),
        ),
    ]
