# Generated by Django 5.2.1 on 2025-05-24 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_banktransferdetails_company_bank_account_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='external_reference',
            field=models.CharField(blank=True, help_text='External reference ID from payment gateway (if applicable)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='internal_reference',
            field=models.CharField(blank=True, help_text='Unique internal reference for tracking this payment', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
