# Generated by Django 5.2.1 on 2025-05-24 12:27

import django.db.models.deletion
import referrals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_alter_referral_referred_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='referrals.referralcode'),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='code',
            field=models.CharField(default=referrals.models.generate_referral_code, max_length=4, unique=True),
        ),
    ]
